In [1]:
import sys
import itertools
import atomium
sys.path.append('../../graph_toolbox/')
from feature import calc_named
from parse.read_library_free import read_pdb_basic, read_pdb, find_cba_atoms, read_pdb_full
from feature.calc import calc_struct_properties
from parse.atomium_utils import atomium_select, atomium_chain_pdb_list

### Truncate sequences

In [2]:
def ordered_atomium(path):
    struct = atomium.open(path).model
    pdb_list = atomium_chain_pdb_list(struct)
    return atomium_select(struct, pdb_list=pdb_list, chain='A')

In [3]:
p = 'data/6iii.pdb'

In [4]:
#%timeit ordered_atomium(p)

In [5]:
#%timeit read_pdb(p)

In [6]:
#%timeit read_pdb_basic(p)

In [7]:
%timeit read_pdb_full(p)

21.1 ms ± 597 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
cb_
cb_xyz_list = list()
cb_nan = np.array((np.nan, np.nan, np.nan), dtype=np.float32)
pos_start = 0
for resid, resiter in itertools.groupby(d.resid):
    num_resatom = len(list(resiter))
    pos_end = pos_start + num_resatom
    resatoms = itertools.islice(d.resatom, pos_start, pos_end)
    res_cb = cb_nan#.copy()
    for i, at in enumerate(resatoms):
        if at == 'CB':
            res_cb = d.xyz[i+pos_start].copy()
            break
    cb_xyz_list.append(res_cb)
    pos_start = pos_end
cb = np.asarray(cb_xyz_list)
        


NameError: name 'cb_' is not defined

In [ ]:
cb_xyz_list

[array([  3.76 ,  58.268, 142.474], dtype=float32),
 array([  1.788,  58.029, 147.516], dtype=float32),
 array([ -3.742,  58.013, 145.992], dtype=float32),
 array([ -2.713,  60.778, 151.21 ], dtype=float32),
 array([ -8.304,  60.053, 151.067], dtype=float32),
 array([ -8.404,  64.651, 154.055], dtype=float32),
 array([-11.25 ,  59.263, 154.785], dtype=float32),
 array([ -9.939,  60.272, 159.747], dtype=float32),
 array([ -9.203,  65.247, 158.208], dtype=float32),
 array([-13.412,  65.239, 155.174], dtype=float32),
 array([-15.99 ,  61.548, 157.364], dtype=float32),
 array([-14.507,  61.579, 162.189], dtype=float32),
 array([-15.569,  67.595, 162.28 ], dtype=float32),
 array([-15.441,  67.524, 167.138], dtype=float32),
 array([-12.774,  62.403, 166.327], dtype=float32),
 array([ -8.441,  64.485, 165.179], dtype=float32),
 array([ -5.722,  68.313, 168.062], dtype=float32),
 array([ -4.983,  69.931, 162.585], dtype=float32),
 array([ -0.498,  68.957, 165.899], dtype=float32),
 array([  3.

In [ ]:
cb_xyz_list

[array([  3.76 ,  58.268, 142.474], dtype=float32),
 array([  1.788,  58.029, 147.516], dtype=float32),
 array([ -3.742,  58.013, 145.992], dtype=float32),
 array([ -2.713,  60.778, 151.21 ], dtype=float32),
 array([ -8.304,  60.053, 151.067], dtype=float32),
 array([ -8.404,  64.651, 154.055], dtype=float32),
 array([-11.25 ,  59.263, 154.785], dtype=float32),
 array([ -9.939,  60.272, 159.747], dtype=float32),
 array([ -9.203,  65.247, 158.208], dtype=float32),
 array([-13.412,  65.239, 155.174], dtype=float32),
 array([-15.99 ,  61.548, 157.364], dtype=float32),
 array([-14.507,  61.579, 162.189], dtype=float32),
 array([-15.569,  67.595, 162.28 ], dtype=float32),
 array([-15.441,  67.524, 167.138], dtype=float32),
 array([-12.774,  62.403, 166.327], dtype=float32),
 array([ -8.441,  64.485, 165.179], dtype=float32),
 array([ -5.722,  68.313, 168.062], dtype=float32),
 array([ -4.983,  69.931, 162.585], dtype=float32),
 array([ -0.498,  68.957, 165.899], dtype=float32),
 array([  3.